# Generated by Django 6.0.2 on 2026-03-06 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Emp',
            new_name='Emp1',
        ),
    ]
